package by.jd2.p1.task1.controller.command;

public enum CommandName {
	LOGINATION, REGISTRATION, SAVENEWUSER, GOTOINDEXPAGE, GOTOMAINPAGE, LOGOUT, GOTOONEFULLNEWS, GOTOEDITFULLNEWS, SAVEEDITFULLNEWS,
	GOTOEDITUSER, SAVEEDITUSER, GOTODELETENEWS, GOTOADDNEWS, SAVEADDNEWS

}
